import React, { createContext, useState, useContext, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type LanguageCode = 'en' | 'hi' | 'mr' | 'gu' | 'ta' | 'te';

export const LANGUAGES: { code: LanguageCode; label: string }[] = [
    { code: 'en', label: 'English' },
    { code: 'hi', label: 'हिन्दी (Hindi)' },
    { code: 'mr', label: 'मराठी (Marathi)' },
    { code: 'gu', label: 'ગુજરાતી (Gujarati)' },
    { code: 'ta', label: 'தமிழ் (Tamil)' },
    { code: 'te', label: 'తెలుగు (Telugu)' },
];

const translations: Record<LanguageCode, Record<string, string>> = {
    en: {
        home: "Home",
        shop: "Shop",
        cart: "Cart",
        profile: "Profile",
        hello: "Hello",
        login_to_view: "Login to view profile",
        my_orders: "My Orders",
        my_wishlist: "My Wishlist",
        my_addresses: "My Addresses",
        account_settings: "Account Settings",
        edit_profile: "Edit Profile",
        saved_addresses: "Saved Addresses",
        payment_methods: "Payment Methods",
        security_password: "Security & Password",
        notifications: "Notifications",
        select_language: "Select Language",
        app_preferences: "App Preferences",
        dark_mode: "Dark Mode",
        download_invoices: "Download Invoices",
        my_activity: "My Activity",
        reviews_ratings: "Reviews & Ratings",
        questions_answers: "Questions & Answers",
        my_chats: "My Chats",
        earn_rewards: "Earn & Rewards",
        refer_earn: "Refer & Earn",
        my_wallet: "My Wallet",
        feedback_info: "Feedback & Information",
        terms_policies: "Terms, Policies and Licenses",
        privacy_policy: "Privacy Policy",
        about_us: "About Us",
        log_out: "Log Out",
        guest_user: "Guest User",

        search_hint: "Search for products...",
        shop_by_category: "Shop by Category",
        view_all: "View All",
        best_sellers: "Best Sellers",
        most_loved: "Most Loved Styles",
        festive_specials: "Festive Specials",
        trending_now: "Trending Now",
        curated_collections: "Curated Collections",
        about: "About",
        contact: "Contact",
        menu: "Menu",
        sign_in: "Sign In",
        searching: "Searching...",
        no_results: "No products found",
        collection: "Collection",
        men: "Men",
        women: "Women",
        boys: "Boys",
        girls: "Girls",
        sishu: "Sishu",
        silk: "Silk",
        cotton: "Cotton",
        regional: "Regional",
        banarasi: "Banarasi",
        designer_sarees: "Designer Sarees",
        printed_sarees: "Printed Sarees",
        all_collection: "All Collection",
        silk_sarees: "Silk Sarees",
        cotton_sarees: "Cotton Sarees",
        regional_sarees: "Regional Sarees",
        banarasi_silk: "Banarasi Silk",
        // Subcategories
        swadhyaya_collection: "Swadhyaya collection",
        sundowner_collection: "Sundowner collection",
        deewangi_collection: "Deewangi collection",
        mehrang_collection: "Mehrang collection",
        virsa_collection: "Virsa collection",
        barati_broz: "Barati broz",
        kurtas: "Kurtas",
        men_kurta_sets: "Men Kurta Sets",
        kurta_dupatta_sets: "Kurta Dupatta Sets",
        sherwanis: "Sherwanis",
        men_nehru_jackets: "Men Nehru Jackets",
        blazers: "Blazers",
        bottomwear: "Bottomwear",
        tshirt: "TShirt",
        kurtis: "Kurtis",
        women_kurti_sets: "Women Kurti Sets",
        women_comfort_wear: "Women Comfort Wear",
        dress: "Dress",
        girls_kurti_set: "Girls Kurti Set",
        lehenga_set: "Lehenga Set",
        anarkali: "Anarkali",
        girls_comfort_wear: "Girls Comfort Wear",
        sishu_boys: "Sishu Boys",
        sishu_girls: "Sishu Girls",
        soft_silk_sarees: "SOFT SILK SAREES",
        kanjivaram_silk_sarees: "KANJIVARAM SILK SAREES",
        banarasi_silk_sarees: "BANARASI SILK SAREES",
        maheshwari_silk_sarees: "MAHESHWARI SILK SAREES",
        raw_silk_sarees: "RAW SILK SAREES",
        mysore_silk_sarees: "MYSORE SILK SAREES",
        sambalpuri_silk_sarees: "SAMBALPURI SILK SAREES",
        kalamkari_print_silk_sarees: "KALAMKARI PRINT SILK SAREES",
        bengali_cotton_sarees: "BENGALI COTTON SAREES",
        maheshwari_cotton_sarees: "MAHESHWARI COTTON SAREES",
        jaipur_cotton_sarees: "JAIPUR COTTON SAREES",
        south_cotton_sarees: "SOUTH COTTON SAREES",
        office_wear_cotton_sarees: "OFFICE WEAR COTTON SAREES",
        dr_khadi_cotton_sarees: "DR.KHADI COTTON SAREES",
        block_printed_cotton_sarees: "BLOCK PRINTED COTTON SAREES",
        bagru_print_cotton_sarees: "BAGRU PRINT COTTON SAREES",
        ajrakh_print_cotton_sarees: "AJRAKH PRINT COTTON SAREES",
        ikkat_cotton_sarees: "IKKAT COTTON SAREES",
        kalamkari_cotton_sarees: "KALAMKARI COTTON SAREES",
        sambalpuri_regional_sarees: "SAMBALPURI REGIONAL SAREES",
        kanjivaram_regional_sarees: "KANJIVARAM REGIONAL SAREES",
        bengali_regional_sarees: "BENGALI REGIONAL SAREES",
        mysore_regional_sarees: "MYSORE REGIONAL SAREES",
        maheshwari_regional_sarees: "MAHESHWARI REGIONAL SAREES",
        karnataka_regional_sarees: "KARNATAKA REGIONAL SAREES",
        tamilnadu_regional_sarees: "TAMILNADU REGIONAL SAREES",
        banarasi_regional_sarees: "BANARASI REGIONAL SAREES",
        banarasi_regional_dupatta: "BANARASI REGIONAL DUPATTA",
        banarasi_sarees: "BANARASI SAREES",
        banarasi_dupatta: "BANARASI DUPATTA",
        banarasi_dress_material: "BANARASI DRESS MATERIAL",
        party_wear_saree: "PARTY WEAR SAREE",
        wedding_sarees: "WEDDING SAREES",
        festive_sarees: "FESTIVE SAREES",
        bollywood_style_sarees: "BOLLYWOOD STYLE SAREES",
        heavy_embroidered_sarees: "HEAVY EMBROIDERED SAREES",
        floral_printed_sarees: "FLORAL PRINTED SAREES",
        digital_printed_sarees: "DIGITAL PRINTED SAREES",
        block_printed_sarees: "BLOCK PRINTED SAREES",
        abstract_printed_sarees: "ABSTRACT PRINTED SAREES",
        geometric_printed_sarees: "GEOMETRIC PRINTED SAREES",
        discount_off: "OFF",
        inclusive_taxes: "Inclusive of all taxes",
        select_size: "Select Size",
        product_details: "Product Details",
        material: "Material",
        color: "Color",
        pattern: "Pattern",
        return_policy: "7 Day Return & Exchange",
        cod_available: "Cash on Delivery Available",
        add_to_cart: "ADD TO CART",
        buy_now: "BUY NOW",
        cart_title: "My Cart",
        step_cart: "Cart",
        step_address: "Address",
        step_payment: "Payment",
        remove_item: "Remove Item",
        remove_item_msg: "Do you want to remove this item from your cart?",
        cancel: "Cancel",
        remove: "Remove",
        size: "Size",
        delivery_by: "Delivery by",
        free: "FREE",
        empty_cart: "Your Cart is Empty",
        empty_cart_msg: "Looks like you haven't added anything to your cart yet.",
        start_shopping: "Start Shopping",
        price_details: "Price Details",
        total_mrp: "Total MRP",
        discount_on_mrp: "Discount on MRP",
        shipping_fee: "Shipping Fee",
        total_amount: "Total Amount",
        you_save: "You will save ₹", // Split string for logic
        on_order: " on this order",
        secure_payments: "100% Secure Payments",
        easy_returns: "Easy Returns",
        authentic_products: "Authentic Products",
        place_order: "Place Order",
        add_items_worth: "Add items worth ₹",
        for_free_delivery: " for FREE Delivery",
        login_title: "Login",
        register_title: "Register",
        email_placeholder: "Email Address",
        email_label: "Email ID",
        password_placeholder: "Password",
        password_label: "Password",
        phone_placeholder: "Phone Number",
        phone_label: "Mobile Number",
        otp_placeholder: "Enter OTP",
        first_name: "First Name",
        last_name: "Last Name",
        confirm_password: "Confirm Password",
        agree_terms: "I agree to Terms & Conditions",
        send_otp: "Send OTP",
        verify_otp: "Verify OTP",
        login_with_otp: "Login with OTP",
        login_with_password: "Login with Password",
        or_login_with: "Or Login with",
        dont_have_account: "Don't have an account?",
        already_have_account: "Already have an account?",
        forgot_password: "Forgot Password?",
        resend_otp: "Resend OTP",
        otp_sent: "OTP sent to your phone number",
        fill_all_fields: "Please fill in all required fields",
        passwords_no_match: "Passwords do not match",
        password_short: "Password must be at least 6 characters",
        agree_terms_err: "Please agree to the terms and conditions",
        phone_not_registered: "Phone number not registered. Please sign up first.",

        invalid_phone: "Please enter a valid 10-digit phone number",
        invalid_email: "Please enter a valid email address",
        collections: "Collections",
        items: "Items",
        sort: "Sort",
        filter: "Filter",
        clear_filters: "Clear Filters",
        sort_by: "Sort By",
        sort_relevant: "Relevant",
        sort_low_high: "Price: Low to High",
        sort_high_low: "Price: High to Low",
        sort_newest: "Newest First",
        filters: "Filters",
        reset: "Reset",
        price_range: "Price Range",
        fabric: "Fabric",
        apply: "Apply",
        empty_wishlist: "Your Wishlist is Empty",
        empty_wishlist_msg: "Tap the heart on any product to save it here.",

        browse_products: "Browse Products",
        review_order: "Review Order",
        delivery_address: "Delivery Address",
        change: "CHANGE",
        edit_address: "Edit Address",
        add_new_address: "Add New Address",
        full_name: "Full Name",
        address_type_home: "Home",
        address_type_work: "Work",
        save_address: "SAVE ADDRESS",
        delete_address: "Delete this address",
        order_summary: "Order Summary",
        total_items: "Total Items",
        total_price: "Total Price",
        payment_options: "Payment Options",
        cod_label: "Cash on Delivery",
        cod_desc: "Pay when you receive the order",
        payu_desc: "Pay securely via PayU",
        price: "Price",
        tax_label: "Tax",
        enter_name: "Enter Name",
        phone_hint: "10-digit number",
        pincode: "Pincode",
        locality: "Locality",
        city: "City",
        state: "State",
        landmark: "Landmark",
        optional: "(Optional)",
        order_placed: "Order Placed!",
        order_confirmed_msg: "Your order has been confirmed successfully.",
        order_id: "Order ID",
        estimated_delivery: "Estimated Delivery",
        check_status: "Check Order Status",
        continue_shopping: "Continue Shopping",
        payment_failed: "Payment Failed",
        payment_failed_msg: "Something went wrong with your transaction. Please try again or choose a different payment method.",
        try_again: "TRY AGAIN",
        go_to_cart: "GO TO CART",
        no_results_for: "No products found for",
        search_retry_msg: "Try checking your spelling or use different keywords",
        type_to_search: "Type to search products",
        about_subtitle: "Weaving Traditions, Draping Dreams",
        our_vision_title: "OUR VISION",
        what_makes_us_special: "WHAT MAKES US SPECIAL?",
        authentic_handloom: "Authentic Handloom Sarees",
        curated_occasion: "Curated for Every Occasion",
        contact_subtitle: "Keep in touch with us",
        store_location_label: "STORE LOCATION",
        company_details_label: "COMPANY DETAILS",
        open_hours_label: "OPEN HOURS",
        terms_subtitle: "Legal Agreement for Platform Usage",
        privacy_subtitle: "Your Privacy Matters to Us",
        shipping_subtitle: "Fast, Reliable, and Secure Delivery",
        shipping_title: "Shipping & Delivery",
        check_email: "Check your email",
        reset_link_sent_msg: "We have sent a password reset link to",
        back_to_login: "Back to Login",
        forgot_password_subtitle: "Don't worry! It happens. Please enter the email associated with your account.",
        send_reset_link: "Send Reset Link",
        redirecting_payment: "Redirecting to Payment...",
        redirecting_gateway: "Please wait, redirecting to payment gateway...",
    },
    hi: {
        home: "होम",
        shop: "शॉप",
        cart: "कार्ट",
        profile: "प्रोफाइल",
        hello: "नमस्ते",
        login_to_view: "प्रोफाइल देखने के लिए लॉगिन करें",
        my_orders: "मेरे ऑर्डर",
        my_wishlist: "मेरी विशलिस्ट",
        my_addresses: "मेरे पते",
        account_settings: "खाता सेटिंग्स",
        edit_profile: "प्रोफाइल बदलें",
        saved_addresses: "सहेजे गए पते",
        payment_methods: "भुगतान विधियां",
        security_password: "सुरक्षा और पासवर्ड",
        notifications: "सूचनाएं",
        select_language: "भाषा चुनें",
        app_preferences: "ऐप प्राथमिकताएं",
        dark_mode: "डार्क मोड",
        download_invoices: "चालान डाउनलोड करें",
        my_activity: "मेरी गतिविधि",
        reviews_ratings: "समीक्षा और रेटिंग",
        questions_answers: "प्रश्न और उत्तर",
        my_chats: "मेरी चैट",
        earn_rewards: "कमाई और पुरस्कार",
        refer_earn: "रेफर करें और कमाएं",
        my_wallet: "मेरा वॉलेट",
        feedback_info: "प्रतिक्रिया और जानकारी",
        terms_policies: "शर्तें, नीतियां और लाइसेंस",
        privacy_policy: "गोपनीयता नीति",
        about_us: "हमारे बारे में",
        log_out: "लॉग आउट",
        guest_user: "अतिथि उपयोगकर्ता",

        search_hint: "उत्पाद खोजें...",
        shop_by_category: "श्रेणी अनुसार खरीदारी",
        view_all: "सभी देखें",
        best_sellers: "सर्वाधिक बिकने वाले",
        most_loved: "सबसे पसंदीदा स्टाइल",
        festive_specials: "त्योहार विशेष",
        trending_now: "अभी ट्रेंडिंग",
        curated_collections: "क्यूरेटेड संग्रह",
        about: "हमारे बारे में",
        contact: "संपर्क करें",
        menu: "मेनू",
        sign_in: "साइन इन",
        searching: "खोज रहा है...",
        no_results: "कोई उत्पाद नहीं मिला",
        collection: "संग्रह",
        men: "पुरुष",
        women: "महिलाएं",
        boys: "लड़के",
        girls: "लड़कियां",
        sishu: "शिशु",
        silk: "सिल्क",
        cotton: "कॉटन",
        regional: "क्षेत्रीय",
        banarasi: "बनारसी",
        designer_sarees: "डिजाइनर साड़ी",
        printed_sarees: "प्रिंटेड साड़ी",
        all_collection: "सभी संग्रह",
        silk_sarees: "सिल्क साड़ी",
        cotton_sarees: "कॉटन साड़ी",
        regional_sarees: "क्षेत्रीय साड़ी",
        banarasi_silk: "बनारसी सिल्क",
        // Subcategories
        swadhyaya_collection: "स्वाध्याय संग्रह",
        sundowner_collection: "सनडाउनर संग्रह",
        deewangi_collection: "दीवानगी संग्रह",
        mehrang_collection: "मेहरंग संग्रह",
        virsa_collection: "विरसा संग्रह",
        barati_broz: "बाराती ब्रोज़",
        kurtas: "कुर्ता",
        men_kurta_sets: "पुरुष कुर्ता सेट",
        kurta_dupatta_sets: "कुर्ता दुपट्टा सेट",
        sherwanis: "शेरवानी",
        men_nehru_jackets: "नेहरू जैकेट",
        blazers: "ब्लेज़र",
        bottomwear: "बॉटमवियर",
        tshirt: "टी-शर्ट",
        kurtis: "कुर्ती",
        women_kurti_sets: "महिला कुर्ती सेट",
        women_comfort_wear: "महिला कम्फर्ट वियर",
        dress: "ड्रेस",
        girls_kurti_set: "गर्ल्स कुर्ती सेट",
        lehenga_set: "लहंगा सेट",
        anarkali: "अनारकली",
        girls_comfort_wear: "गर्ल्स कम्फर्ट वियर",
        sishu_boys: "शिशु - लड़के",
        sishu_girls: "शिशु - लड़कियां",
        soft_silk_sarees: "सॉफ्ट सिल्क साड़ी",
        kanjivaram_silk_sarees: "कांजीवरम सिल्क साड़ी",
        banarasi_silk_sarees: "बनारसी सिल्क साड़ी",
        maheshwari_silk_sarees: "महेश्वरी सिल्क साड़ी",
        raw_silk_sarees: "रॉ सिल्क साड़ी",
        mysore_silk_sarees: "मैसूर सिल्क साड़ी",
        sambalpuri_silk_sarees: "संबलपुरी सिल्क साड़ी",
        kalamkari_print_silk_sarees: "कलामकारी प्रिंट सिल्क साड़ी",
        bengali_cotton_sarees: "बंगाली कॉटन साड़ी",
        maheshwari_cotton_sarees: "महेश्वरी कॉटन साड़ी",
        jaipur_cotton_sarees: "जयपुर कॉटन साड़ी",
        south_cotton_sarees: "साउथ कॉटन साड़ी",
        office_wear_cotton_sarees: "ऑफिस वियर कॉटन साड़ी",
        dr_khadi_cotton_sarees: "डॉ. खादी कॉटन साड़ी",
        block_printed_cotton_sarees: "ब्लॉक प्रिंटेड कॉटन साड़ी",
        bagru_print_cotton_sarees: "बगरू प्रिंट कॉटन साड़ी",
        ajrakh_print_cotton_sarees: "अजरख प्रिंट कॉटन साड़ी",
        ikkat_cotton_sarees: "इक्कत कॉटन साड़ी",
        kalamkari_cotton_sarees: "कलामकारी कॉटन साड़ी",
        sambalpuri_regional_sarees: "संबलपुरी क्षेत्रीय साड़ी",
        kanjivaram_regional_sarees: "कांजीवरम क्षेत्रीय साड़ी",
        bengali_regional_sarees: "बंगाली क्षेत्रीय साड़ी",
        mysore_regional_sarees: "मैसूर क्षेत्रीय साड़ी",
        maheshwari_regional_sarees: "महेश्वरी क्षेत्रीय साड़ी",
        karnataka_regional_sarees: "कर्नाटक क्षेत्रीय साड़ी",
        tamilnadu_regional_sarees: "तमिलनाडु क्षेत्रीय साड़ी",
        banarasi_regional_sarees: "बनारसी क्षेत्रीय साड़ी",
        banarasi_regional_dupatta: "बनारसी क्षेत्रीय दुपट्टा",
        banarasi_sarees: "बनारसी साड़ी",
        banarasi_dupatta: "बनारसी दुपट्टा",
        banarasi_dress_material: "बनारसी ड्रेस मटीरियल",
        party_wear_saree: "पार्टी वियर साड़ी",
        wedding_sarees: "वेडिंग साड़ी",
        festive_sarees: "फेस्टिव साड़ी",
        bollywood_style_sarees: "बॉलीवुड स्टाइल साड़ी",
        heavy_embroidered_sarees: "हेवी एम्ब्रॉयडरी साड़ी",
        floral_printed_sarees: "फ्लोरल प्रिंटेड साड़ी",
        digital_printed_sarees: "डिजिटल प्रिंटेड साड़ी",
        block_printed_sarees: "ब्लॉक प्रिंटेड साड़ी",
        abstract_printed_sarees: "एब्सट्रैक्ट प्रिंटेड साड़ी",
        geometric_printed_sarees: "जियोमेट्रिक प्रिंटेड साड़ी",
        discount_off: "छूट",
        inclusive_taxes: "सभी कर शामिल",
        select_size: "साइज चुनें",
        product_details: "उत्पाद विवरण",
        material: "सामग्री",
        color: "रंग",
        pattern: "पैटर्न",
        return_policy: "7 दिन की वापसी और विनिमय",
        cod_available: "कैश ऑन डिलीवरी उपलब्ध",
        add_to_cart: "कार्ट में जोड़ें",
        buy_now: "अभी खरीदें",
        cart_title: "मेरा कार्ट",
        step_cart: "कार्ट",
        step_address: "पता",
        step_payment: "भुगतान",
        remove_item: "आइटम हटाएं",
        remove_item_msg: "क्या आप इसे हटाना चाहते हैं?",
        cancel: "रद्द करें",
        remove: "हटाएं",
        size: "साइज",
        delivery_by: "डिलिवरी",
        free: "मुफ़्त",
        empty_cart: "आपकी कार्ट खाली है",
        empty_cart_msg: "आपने अभी तक कुछ नहीं जोड़ा है।",
        start_shopping: "खरीदारी शुरू करें",
        price_details: "मूल्य विवरण",
        total_mrp: "कुल एमआरपी",
        discount_on_mrp: "एमआरपी पर छूट",
        shipping_fee: "शिपिंग शुल्क",
        total_amount: "कुल राशि",
        you_save: "आप बचाएंगे ₹",
        on_order: " इस ऑर्डर पर",
        secure_payments: "100% सुरक्षित भुगतान",
        easy_returns: "आसान रिटर्न",
        authentic_products: "असली उत्पाद",
        place_order: "ऑर्डर करें",
        add_items_worth: "मुफ्त डिलीवरी के लिए ₹",
        for_free_delivery: " का और सामान जोड़ें",
        login_title: "लॉगिन",
        register_title: "रजिस्टर",
        email_placeholder: "ईमेल पता",
        email_label: "ईमेल आईडी",
        password_placeholder: "पासवर्ड",
        password_label: "पासवर्ड",
        phone_placeholder: "फोन नंबर",
        phone_label: "मोबाइल नंबर",
        otp_placeholder: "ओटीपी दर्ज करें",
        first_name: "पहला नाम",
        last_name: "अंतिम नाम",
        confirm_password: "पासवर्ड की पुष्टि करें",
        agree_terms: "मैं नियम और शर्तों से सहमत हूं",
        send_otp: "ओटीपी भेजें",
        verify_otp: "ओटीपी सत्यापित करें",
        login_with_otp: "ओटीपी के साथ लॉगिन करें",
        login_with_password: "पासवर्ड के साथ लॉगिन करें",
        or_login_with: "या लॉगिन करें",
        dont_have_account: "खाता नहीं है?",
        already_have_account: "क्या आपके पास पहले से एक खाता मौजूद है?",
        forgot_password: "पासवर्ड भूल गए?",
        resend_otp: "ओटीपी पुनः भेजें",
        otp_sent: "आपके फोन नंबर पर ओटीपी भेजा गया",
        fill_all_fields: "कृपया सभी आवश्यक क्षेत्र भरें",
        passwords_no_match: "पासवर्ड मेल नहीं खाते",
        password_short: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
        agree_terms_err: "कृपया नियम और शर्तों से सहमत हों",
        phone_not_registered: "फोन नंबर पंजीकृत नहीं है। कृपया पहले साइन अप करें।",
        invalid_phone: "कृपया मान्य 10-अंकीय फोन नंबर दर्ज करें",
        invalid_email: "कृपया मान्य ईमेल पता दर्ज करें",
        collections: "कलेक्शन",
        items: "आइटम",
        sort: "क्रम",
        filter: "फ़िल्टर",
        clear_filters: "फ़िल्टर हटाएं",
        sort_by: "क्रमबद्ध करें",
        sort_relevant: "प्रासंगिक",
        sort_low_high: "कीमत: कम से ज्यादा",
        sort_high_low: "कीमत: ज्यादा से कम",
        sort_newest: "नया पहले",
        filters: "फ़िल्टर",
        reset: "रीसेट",
        price_range: "कीमत सीमा",
        fabric: "कपड़ा",
        apply: "लागू करें",
        empty_wishlist: "आपकी विशलिस्ट खाली है",
        empty_wishlist_msg: "उत्पाद को यहाँ सहेजने के लिए दिल के निशान पर टैप करें।",
        browse_products: "उत्पाद ब्राउज़ करें",
        review_order: "ऑर्डर की समीक्षा करें",
        delivery_address: "डिलीवरी का पता",
        change: "बदलें",
        edit_address: "पता संपादित करें",
        add_new_address: "नया पता जोड़ें",
        full_name: "पूरा नाम",
        address_type_home: "घर",
        address_type_work: "कार्यस्थल",
        save_address: "पता सहेजें",
        delete_address: "यह पता हटाएं",
        order_summary: "ऑर्डर सारांश",
        total_items: "कुल आइटम",
        total_price: "कुल मूल्य",
        payment_options: "भुगतान विकल्प",
        cod_label: "कैश ऑन डिलीवरी",
        cod_desc: "ऑर्डर मिलने पर भुगतान करें",
        payu_desc: "PayU के माध्यम से सुरक्षित भुगतान करें",
        price: "मूल्य",
        tax_label: "कर",
        enter_name: "नाम दर्ज करें",
        phone_hint: "10-अंकीय नंबर",
        pincode: "पिनकोड",
        locality: "इलाका",
        city: "शहर",
        state: "राज्य",
        landmark: "लैंडमार्क",
        optional: "(वैकल्पिक)",
        order_placed: "ऑर्डर, सफलतापूर्वक दे दिया!",
        order_confirmed_msg: "आपका ऑर्डर सफलतापूर्वक पुष्टि कर दिया गया है।",
        order_id: "ऑर्डर आईडी",
        estimated_delivery: "अनुमानित डिलीवरी",
        check_status: "ऑर्डर की स्थिति जांचें",
        continue_shopping: "खरीदारी जारी रखें",
        payment_failed: "भुगतान विफल",
        payment_failed_msg: "आपके लेनदेन में कुछ गलत हो गया। कृपया पुन: प्रयास करें या एक अलग भुगतान विधि चुनें।",
        try_again: "पुनः प्रयास करें",
        go_to_cart: "कार्ट पर जाएं",
        no_results_for: "इसके लिए कोई उत्पाद नहीं मिला",
        search_retry_msg: "पनी वर्तनी की जाँच करें या अलग कीवर्ड का उपयोग करें",
        type_to_search: "उत्पाद खोजने के लिए टाइप करें",
        about_subtitle: "परंपरा को बुनना, सपनों को सजाना",
        our_vision_title: "हमारी दृष्टि",
        what_makes_us_special: "हमें क्या खास बनाता है?",
        authentic_handloom: "असली हैंडलूम साड़ी",
        curated_occasion: "हर अवसर के लिए क्यूरेट किया गया",
        contact_subtitle: "हमसे जुड़े रहें",
        store_location_label: "स्टोर का पता",
        company_details_label: "कंपनी विवरण",
        open_hours_label: "खुलने का समय",
        terms_subtitle: "मंच उपयोग के लिए कानूनी समझौता",
        privacy_subtitle: "आपकी गोपनीयता हमारे लिए मायने रखती है",
        shipping_subtitle: "तेज, विश्वसनीय और सुरक्षित डिलीवरी",
        shipping_title: "शिपिंग और डिलीवरी",
        check_email: "अपना ईमेल जांचें",
        reset_link_sent_msg: "हमने पासवर्ड रीसेट लिंक भेजा है",
        back_to_login: "लॉगिन पर वापस जाएं",
        forgot_password_subtitle: "चिंता न करें! अपने खाते से जुड़ा ईमेल दर्ज करें।",
        send_reset_link: "रीसेट लिंक भेजें",
        redirecting_payment: "भुगतान के लिए रीडायरेक्ट किया जा रहा है...",
        redirecting_gateway: "कृपया प्रतीक्षा करें, हम आपको भुगतान गेटवे पर भेज रहे हैं...",
    },
    mr: {
        home: "होम",
        shop: "कापड",
        cart: "कार्ट",
        profile: "प्रोफाइल",
        hello: "नमस्कार",
        login_to_view: "प्रोफाइल पाहण्यासाठी लॉगिन करा",
        my_orders: "माझ्या ऑर्डर",
        my_wishlist: "माझी विशलिस्ट",
        my_addresses: "माझे पत्ते",
        account_settings: "खाते सेटिंग्ज",
        edit_profile: "प्रोफाइल संपादित करा",
        saved_addresses: "जतन केलेले पत्ते",
        payment_methods: "पेमेंट पद्धती",
        security_password: "सुरक्षा आणि पासवर्ड",
        notifications: "सूचना",
        select_language: "भाषा निवडा",
        app_preferences: "अॅप प्राधान्ये",
        dark_mode: "डार्क मोड",
        download_invoices: "इनव्हॉइस डाउनलोड करा",
        my_activity: "माझी क्रियाकलाप",
        reviews_ratings: "पुनरावलोकने आणि रेटिंग",
        questions_answers: "प्रश्न आणि उत्तरे",
        my_chats: "माझ्या गप्पा",
        earn_rewards: "कमाई आणि बक्षीस",
        refer_earn: "रेफर करा आणि कमवा",
        my_wallet: "माझे वॉलेट",
        feedback_info: "अभिप्राय आणि माहिती",
        terms_policies: "अटी, धोरणे आणि परवाने",
        privacy_policy: "गोपनीयता धोरण",
        about_us: "आमच्याबद्दल",
        log_out: "लॉग आउट",
        guest_user: "पाहुणे वापरकर्ता",

        search_hint: "उत्पादने शोधा...",
        shop_by_category: "श्रेणीनुसार खरेदी",
        view_all: "सर्व पहा",
        best_sellers: "सर्वाधिक खपलेली",
        most_loved: "सर्वात लोकप्रिय",
        festive_specials: "सण विशेष",
        trending_now: "सध्या ट्रेंडिंग",
        curated_collections: "निवडक संग्रह",
        about: "आमच्याबद्दल",
        contact: "संपर्क",
        menu: "मेनू",
        sign_in: "साइन इन",
        searching: "शोधत आहे...",
        no_results: "काहीही सापडले नाही",
        collection: "संग्रह",
        men: "पुरुष",
        women: "स्त्रिया",
        boys: "मुले",
        girls: "मुली",
        sishu: "शिशू",
        silk: "रेशीम",
        cotton: "सुती",
        regional: "प्रादेशिक",
        banarasi: "बनारसी",
        designer_sarees: "डिझायनर साड्या",
        printed_sarees: "प्रिंटेड साड्या",
        all_collection: "सर्व संग्रह",
        silk_sarees: "सिल्क साडी",
        cotton_sarees: "कॉटन साडी",
        regional_sarees: "प्रादेशिक साडी",
        banarasi_silk: "बनारसी सिल्क",
        // Subcategories
        swadhyaya_collection: "स्वाध्याय संग्रह",
        sundowner_collection: "सनडाउनर संग्रह",
        deewangi_collection: "दीवानगी संग्रह",
        mehrang_collection: "मेहरंग संग्रह",
        virsa_collection: "विरसा संग्रह",
        barati_broz: "बाराती ब्रोज़",
        kurtas: "कुर्ता",
        men_kurta_sets: "पुरुष कुर्ता सेट",
        kurta_dupatta_sets: "कुर्ता दुपट्टा सेट",
        sherwanis: "शेरवानी",
        men_nehru_jackets: "नेहरू जॅकेट",
        blazers: "ब्लेझर",
        bottomwear: "बॉटमवियर",
        tshirt: "टी-शर्ट",
        kurtis: "कुर्ती",
        women_kurti_sets: "महिला कुर्ती सेट",
        women_comfort_wear: "महिला कम्फर्ट वियर",
        dress: "ड्रेस",
        girls_kurti_set: "गर्ल्स कुर्ती सेट",
        lehenga_set: "लेहेंगा सेट",
        anarkali: "अनारकली",
        girls_comfort_wear: "गर्ल्स कम्फर्ट वियर",
        sishu_boys: "शिशु - मुले",
        sishu_girls: "शिशु - मुली",
        soft_silk_sarees: "सॉफ्ट सिल्क साडी",
        kanjivaram_silk_sarees: "कांजीवरम सिल्क साडी",
        banarasi_silk_sarees: "बनारसी सिल्क साडी",
        maheshwari_silk_sarees: "महेश्वरी सिल्क साडी",
        raw_silk_sarees: "रॉ सिल्क साडी",
        mysore_silk_sarees: "मैसूर सिल्क साडी",
        sambalpuri_silk_sarees: "संबलपुरी सिल्क साडी",
        kalamkari_print_silk_sarees: "कलामकारी प्रिंट सिल्क साडी",
        bengali_cotton_sarees: "बंगाली कॉटन साडी",
        maheshwari_cotton_sarees: "महेश्वरी कॉटन साडी",
        jaipur_cotton_sarees: "जयपूर कॉटन साडी",
        south_cotton_sarees: "साउथ कॉटन साडी",
        office_wear_cotton_sarees: "ऑफिस वियर कॉटन साडी",
        dr_khadi_cotton_sarees: "डॉ. खादी कॉटन साडी",
        block_printed_cotton_sarees: "ब्लॉक प्रिंटेड कॉटन साडी",
        bagru_print_cotton_sarees: "बगरू प्रिंट कॉटन साडी",
        ajrakh_print_cotton_sarees: "अजरख प्रिंट कॉटन साडी",
        ikkat_cotton_sarees: "इक्कत कॉटन साडी",
        kalamkari_cotton_sarees: "कलामकारी कॉटन साडी",
        sambalpuri_regional_sarees: "संबलपुरी प्रादेशिक साडी",
        kanjivaram_regional_sarees: "कांजीवरम प्रादेशिक साडी",
        bengali_regional_sarees: "बंगाली प्रादेशिक साडी",
        mysore_regional_sarees: "मैसूर प्रादेशिक साडी",
        maheshwari_regional_sarees: "महेश्वरी प्रादेशिक साडी",
        karnataka_regional_sarees: "कर्नाटक प्रादेशिक साडी",
        tamilnadu_regional_sarees: "तामिळनाडू प्रादेशिक साडी",
        banarasi_regional_sarees: "बनारसी प्रादेशिक साडी",
        banarasi_regional_dupatta: "बनारसी प्रादेशिक दुपट्टा",
        banarasi_sarees: "बनारसी साडी",
        banarasi_dupatta: "बनारसी दुपट्टा",
        banarasi_dress_material: "बनारसी ड्रेस मटेरियल",
        party_wear_saree: "पार्टी वियर साडी",
        wedding_sarees: "वेडिंग साडी",
        festive_sarees: "फेस्टिव साडी",
        bollywood_style_sarees: "बॉलीवूड स्टाईल साडी",
        heavy_embroidered_sarees: "हेवी एम्ब्रॉयडरी साडी",
        floral_printed_sarees: "फ्लोरल प्रिंटेड साडी",
        digital_printed_sarees: "डिजिटल प्रिंटेड साडी",
        block_printed_sarees: "ब्लॉक प्रिंटेड साडी",
        abstract_printed_sarees: "अॅबस्ट्रॅक्ट प्रिंटेड साडी",
        geometric_printed_sarees: "जिओमेट्रिक प्रिंटेड साडी",
        discount_off: "सूट",
        inclusive_taxes: "सर्व कर समाविष्ट",
        select_size: "साइज निवडा",
        product_details: "उत्पादन तपशील",
        material: "साहित्य",
        color: "रंग",
        pattern: "पैटर्न",
        return_policy: "7 दिवस परतावा आणि विनिमय",
        cod_available: "कॅश ऑन डिलिव्हरी उपलब्ध",
        add_to_cart: "कार्टमध्ये जोडा",
        buy_now: "आता खरेदी करा",
        cart_title: "माझे कार्ट",
        step_cart: "कार्ट",
        step_address: "पत्ता",
        step_payment: "पेमेंट",
        remove_item: "आयटम काढा",
        remove_item_msg: "तुम्हाला हे काढायचे आहे का?",
        cancel: "रद्द करा",
        remove: "काढा",
        size: "साइज",
        delivery_by: "डिलिव्हरी",
        free: "मोफत",
        empty_cart: "तुमची कार्ट रिकामी आहे",
        empty_cart_msg: "तुम्ही काहीही जोडलेले नाही.",
        start_shopping: "खरेदी सुरू करा",
        price_details: "किंमत तपशील",
        total_mrp: "एकूण एमआरपी",
        discount_on_mrp: "एमआरपीवर सूट",
        shipping_fee: "शिपिंग शुल्क",
        total_amount: "एकूण रक्कम",
        you_save: "तुम्ही वाचवाल ₹",
        on_order: " या ऑर्डरवर",
        secure_payments: "100% सुरक्षित पेमेंट",
        easy_returns: "सोपे रिटर्न",
        authentic_products: "अस्सल उत्पादने",
        place_order: "ऑर्डर द्या",
        add_items_worth: "मोफत डिलिव्हरीसाठी ₹",
        for_free_delivery: " चे सामान जोडा",
        login_title: "लॉगिन",
        register_title: "नोंदणी",
        email_placeholder: "ईमेल पत्ता",
        email_label: "ईमेल आयडी",
        password_placeholder: "पासवर्ड",
        password_label: "पासवर्ड",
        phone_placeholder: "फोन नंबर",
        phone_label: "मोबाईल नंबर",
        otp_placeholder: "ओटीपी प्रविष्ट करा",
        first_name: "पहिले नाव",
        last_name: "आडनाव",
        confirm_password: "पासवर्डची पुष्टी करा",
        agree_terms: "मी अटी आणि शर्तींशी सहमत आहे",
        send_otp: "ओटीपी पाठवा",
        verify_otp: "ओटीपी सत्यापित करा",
        login_with_otp: "ओटीपीसह लॉगिन करा",
        login_with_password: "पासवर्डसह लॉगिन करा",
        or_login_with: "किंवा लॉगिन करा",
        dont_have_account: "खाते नाही?",
        already_have_account: "आधीच खाते आहे?",
        forgot_password: "पासवर्ड विसरलात?",
        resend_otp: "ओटीपी पुन्हा पाठवा",
        otp_sent: "तुमच्या फोन नंबरवर ओटीपी पाठवला",
        fill_all_fields: "कृपया सर्व आवश्यक फील्ड भरा",
        passwords_no_match: "पासवर्ड जुळत नाहीत",
        password_short: "पासवर्ड किमान 6 अक्षरांचा असावा",
        agree_terms_err: "कृपया अटी आणि शर्तींशी सहमत व्हा",
        phone_not_registered: "फोन नंबर नोंदणीकृत नाही. कृपया आधी साइन अप करा.",
        invalid_phone: "कृपया वैध 10-अंकी फोन नंबर प्रविष्ट करा",
        invalid_email: "कृपया वैध ईमेल पत्ता प्रविष्ट करा",
        collections: "कलेक्शन",
        items: "आयटम",
        sort: "क्रमवारी",
        filter: "फिल्टर",
        clear_filters: "फिल्टर काढा",
        sort_by: "क्रमवारी लावा",
        sort_relevant: "संबंधित",
        sort_low_high: "किंमत: कमी ते जास्त",
        sort_high_low: "किंमत: जास्त ते कमी",
        sort_newest: "नवीन प्रथम",
        filters: "फिल्टर",
        reset: "रिसेट",
        price_range: "किंमत श्रेणी",
        fabric: "कापड",
        apply: "लागू करा",
        empty_wishlist: "तुमची विशलिस्ट रिकामी आहे",
        empty_wishlist_msg: "येथे जतन करण्यासाठी कोणत्याही उत्पादनावरील हृदयावर टॅप करा.",
        browse_products: "उत्पादने ब्राउझ करा",
        review_order: "ऑर्डरचे पुनरावलोकन करा",
        delivery_address: "डिलिव्हरी पत्ता",
        change: "बदला",
        edit_address: "पत्ता संपादित करा",
        add_new_address: "नवीन पत्ता जोडा",
        full_name: "पूर्ण नाव",
        address_type_home: "घर",
        address_type_work: "कामाचे ठिकाण",
        save_address: "पत्ता जतन करा",
        delete_address: "हा पत्ता काढा",
        order_summary: "ऑर्डर सारांश",
        total_items: "एकूण आयटम",
        total_price: "एकूण किंमत",
        payment_options: "पेमेंट पर्याय",
        cod_label: "कॅश ऑन डिलिव्हरी",
        cod_desc: "ऑर्डर मिळाल्यावर पैसे द्या",
        payu_desc: "PayU द्वारे सुरक्षित पेमेंट करा",
        price: "किंमत",
        tax_label: "कर",
        enter_name: "नाव एंटर करा",
        phone_hint: "10-अंकी क्रमांक",
        pincode: "पिनकोड",
        locality: "परिसर",
        city: "शहर",
        state: "राज्य",
        landmark: "लँडमार्क",
        optional: "(पर्यायी)",
        order_placed: "ऑर्डर यशस्वीरित्या दिली!",
        order_confirmed_msg: "तुमच्या ऑर्डरची यशस्वीरित्या पुष्टी झाली आहे.",
        order_id: "ऑर्डर आयडी",
        estimated_delivery: "अंदाजित डिलिव्हरी",
        check_status: "ऑर्डर स्थिती तपासा",
        continue_shopping: "खरेदी सुरू ठेवा",
        payment_failed: "पेमेंट अयशस्वी",
        payment_failed_msg: "तुमच्या व्यवहारात काही तरी चूक झाली. कृपया पुन्हा प्रयत्न करा किंवा वेगळी पेमेंट पद्धत निवडा.",
        try_again: "पुन्हा प्रयत्न करा",
        go_to_cart: "कार्टवर जा",
        no_results_for: "यासाठी कोणतीही उत्पादने सापडली नाहीत",
        search_retry_msg: "तुमचे स्पेलिंग तपासा किंवा वेगळे कीवर्ड वापरा",
        type_to_search: "उत्पादने शोधण्यासाठी टाइप करा",
        about_subtitle: "परंपरा विणणे, स्वप्ने सजवणे",
        our_vision_title: "आमचा दृष्टीकोन",
        what_makes_us_special: "आम्हाला काय खास बनवते?",
        authentic_handloom: "अस्सल हातमाग साड्या",
        curated_occasion: "प्रत्येक प्रसंगासाठी निवडक",
        contact_subtitle: "आमच्या संपर्कात राहा",
        store_location_label: "स्टोअरचे स्थान",
        company_details_label: "कंपनीचे तपशील",
        open_hours_label: "उघडण्याची वेळ",
        terms_subtitle: "प्लॅटफॉर्म वापरण्यासाठी कायदेशीर करार",
        privacy_subtitle: "तुमची गोपनीयता आमच्यासाठी महत्त्वाची आहे",
        shipping_subtitle: "जलद, विश्वासार्ह आणि सुरक्षित डिलिव्हरी",
        shipping_title: "शिपिंग आणि डिलिव्हरी",
        check_email: "तुमचे ईमेल तपासा",
        reset_link_sent_msg: "आम्ही पासवर्ड रीसेट लिंक पाठवले आहे",
        back_to_login: "लॉगिन वर परत जा",
        forgot_password_subtitle: "काळजी करू नका! आपल्या खात्याशी संबंधित ईमेल प्रविष्ट करा.",
        send_reset_link: "रीसेट लिंक पाठवा",
        redirecting_payment: "पेमेंटवर रीडायरेक्ट करत आहे...",
        redirecting_gateway: "कृपया प्रतीक्षा करा, आम्ही तुम्हाला पेमेंट गेटवेवर पाठवत आहोत...",
    },
    gu: {
        address_type_home: "ઘર",
        address_type_work: "કામ",
        home: "હોમ",
        shop: "શોપ",
        cart: "કાર્ટ",
        profile: "પ્રોફાઇલ",
        hello: "નમસ્તે",
        men: "પુરુષો",
        women: "સ્ત્રીઓ",
        boys: "છોકરાઓ",
        girls: "છોકરીઓ",
        sishu: "શિશુ",
        all_collection: "બધા કલેક્શન",
        silk_sarees: "સિલ્ક સાડી",
        cotton_sarees: "કોટન સાડી",
        regional_sarees: "પ્રાદેશિક સાડી",
        banarasi_silk: "બનારસી સિલ્ક",
        designer_sarees: "ડિઝાઇનર સાડી",
        printed_sarees: "પ્રિન્ટેડ સાડી",
        silk: "સિલ્ક",
        cotton: "કોટન",
        regional: "પ્રાદેશિક",
        banarasi: "બનારસી",
        party_wear_saree: "પાર્ટી વેર સાડી",
        wedding_sarees: "લગ્ન સાડી",
        festive_sarees: "તહેવાર સાડી",
        collection: "કલેક્શન",
        collections: "કલેક્શન",
        sort_by: "સૉર્ટ કરો",
        sort_relevant: "સંબંધિત",
        sort_low_high: "કિંમત: લો થી હાઈ",
        sort_high_low: "કિંમત: હાઈ થી લો",
        sort_newest: "નવું પ્રથમ",
        filters: "ફિલ્ટર્સ",
        reset: "રીસેટ",
        price_range: "કિંમત શ્રેણી",
        fabric: "ફેબ્રિક",
        apply: "લાગુ કરો",
        clear_filters: "ફિલ્ટર સાફ કરો",
        material: "સામગ્રી",
        color: "રંગ",
        pattern: "પેટર્ન",
        product_details: "ઉત્પાદન વિગતો",
        select_size: "કદ પસંદ કરો",
        inclusive_taxes: "બધા કર સહિત",
        return_policy: "7 દિવસ રિપ્લેસમેન્ટ",
        cod_available: "કેશ ઓન ડિલિવરી",
        discount_off: "છૂટ",
        account_settings: "એકાઉન્ટ સેટિંગ્સ",
        log_out: "લૉગ આઉટ",
        select_language: "ભાષા પસંદ કરો",
        my_orders: "મારા ઓર્ડર",
        my_wishlist: "મારી વિશલિસ્ટ",
        my_addresses: "મારા સરનામાં",
        saved_addresses: "સાચવેલા સરનામાં",
        contact: "સંપર્ક",
        about_us: "અમારા વિશે",
        privacy_policy: "ગોપનીયતા નીતિ",
        terms_policies: "શરતો અને નીતિઓ",
        login_title: "લૉગિન",
        register_title: "રજીસ્ટર",
        items: "વસ્તુઓ",
        sort: "સૉર્ટ",
        filter: "ફિલ્ટર",
        price: "કિંમત",
        add_to_cart: "કાર્ટમાં ઉમેરો",
        buy_now: "હમણાં ખરીદો",
        search_hint: "ઉત્પાદનો શોધો...",
        order_placed: "ઓર્ડર આપ્યો!",
        order_confirmed_msg: "તમારા ઓર્ડરની સફળતાપૂર્વક પુષ્ટિ કરવામાં આવી છે.",
        check_status: "ઓર્ડર સ્થિતિ તપાસો",
        continue_shopping: "ખરીદી ચાલુ રાખો",
        payment_failed: "ચુકવણી નિષ્ફળ",
        try_again: "ફરીથી પ્રયાસ કરો",
        no_results_for: "માટે કોઈ પરિણામો નથી",
        empty_cart: "તમારું કાર્ટ ખાલી છે",
        empty_wishlist: "તમારી વિશલિસ્ટ ખાલી છે",
    },
    ta: {
        address_type_home: "வீடு",
        address_type_work: "வேலை",
        home: "முகப்பு",
        shop: "கடை",
        cart: "கூடை",
        profile: "சுயவிவரம்",
        hello: "வணக்கம்",
        men: "ஆண்கள்",
        women: "பெண்கள்",
        boys: "சிறுவர்கள்",
        girls: "சிறுமிகள்",
        sishu: "சிசு",
        all_collection: "அனைத்து சேகரிப்பு",
        silk_sarees: "பட்டு புடவைகள்",
        cotton_sarees: "பருத்தி புடவைகள்",
        regional_sarees: "பிராந்திய புடவைகள்",
        banarasi_silk: "பனாரஸி பட்டு",
        designer_sarees: "வடிவமைப்பாளர் புடவைகள்",
        printed_sarees: "அச்சிடப்பட்ட புடவைகள்",
        silk: "பட்டு",
        cotton: "பருத்தி",
        regional: "பிராந்திய",
        banarasi: "பனாரஸி",
        party_wear_saree: "விருந்து புடவை",
        wedding_sarees: "திருமண புடவை",
        festive_sarees: "விழா புடவை",
        collection: "சேகரிப்பு",
        collections: "சேகரிப்புகள்",
        sort_by: "வகைப்படுத்த",
        sort_relevant: "தொடர்புடையது",
        sort_low_high: "விலை: குறைவு முதல் அதிகம்",
        sort_high_low: "விலை: அதிகம் முதல் குறைவு",
        sort_newest: "புதியது முதலில்",
        filters: "வடிப்பிகள்",
        reset: "மீட்டமை",
        price_range: "விலை வரம்பு",
        fabric: "துணி",
        apply: "பயன்படுத்து",
        clear_filters: "வடிப்பிகளை அழி",
        material: "பொருள்",
        color: "நிறம்",
        pattern: "முறை",
        product_details: "தயாரிப்பு விவரங்கள்",
        select_size: "அளவை தேர்வு",
        inclusive_taxes: "அனைத்து வரிகளும் உட்பட",
        return_policy: "7 நாட்கள் மாற்று",
        cod_available: "பணம் சேகரிப்பு உள்ளது",
        discount_off: "தள்ளுபடி",
        account_settings: "கணக்கு அமைப்புகள்",
        log_out: "வெளியேறு",
        select_language: "மொழியைத் தேர்ந்தெடுக்கவும்",
        my_orders: "என் ஆர்டர்கள்",
        my_wishlist: "என் விருப்பப்பட்டியல்",
        my_addresses: "என் முகவரிகள்",
        saved_addresses: "சேமிக்கப்பட்ட முகவரிகள்",
        contact: "தொடர்பு",
        about_us: "எங்களை பற்றி",
        privacy_policy: "தனியுரிமைக் கொள்கை",
        terms_policies: "விதிமுறைகள்",
        login_title: "உள்நுழைய",
        register_title: "பதிவு",
        items: "பொருட்கள்",
        sort: "வகைப்படுத்து",
        filter: "வடிகட்டு",
        price: "விலை",
        add_to_cart: "கூடையில் சேர்",
        buy_now: "வாங்கவும்",
        search_hint: "தேட...",
        order_placed: "ஆர்டர் செய்யப்பட்டது!",
        order_confirmed_msg: "உங்கள் ஆர்டர் உறுதிப்படுத்தப்பட்டது.",
        check_status: "ஆர்டர் நிலை",
        continue_shopping: "தொடரவும்",
        payment_failed: "கட்டணம் தோல்வி",
        try_again: "மீண்டும் முயல்க",
        no_results_for: "முடிவுகள் இல்லை",
        empty_cart: "கூடை காலியாக உள்ளது",
        empty_wishlist: "விருப்பப்பட்டியல் காலியாக உள்ளது",
    },
    te: {
        address_type_home: "ఇల్లు",
        address_type_work: "పని",
        home: "హోమ్",
        shop: "షాపు",
        cart: "కార్ట్",
        profile: "ప్రొఫైల్",
        hello: "నమస్తే",
        men: "పురుషులు",
        women: "స్త్రీలు",
        boys: "బాలురు",
        girls: "బాలికలు",
        sishu: "శిశు",
        all_collection: "అన్ని కలెక్షన్స్",
        silk_sarees: "పట్టు చీరలు",
        cotton_sarees: "కాటన్ చీరలు",
        regional_sarees: "ప్రాంతీయ చీరలు",
        banarasi_silk: "బెనారసి పట్టు",
        designer_sarees: "డిజైనర్ చీరలు",
        printed_sarees: "ప్రింటెడ్ చీరలు",
        silk: "పట్టు",
        cotton: "కాటన్",
        regional: "ప్రాంతీయ",
        banarasi: "బెనారసి",
        party_wear_saree: "పార్టీ వేర్ చీర",
        wedding_sarees: "పెళ్లి చీరలు",
        festive_sarees: "పండగ చీరలు",
        collection: "కలెక్షన్",
        collections: "కలెక్షన్స్",
        sort_by: "సార్ట్ చేయండి",
        sort_relevant: "సంబంధిత",
        sort_low_high: "ధర: తక్కువ నుండి ఎక్కువ",
        sort_high_low: "ధర: ఎక్కువ నుండి తక్కువ",
        sort_newest: "కొత్తవి మొదట",
        filters: "ఫిల్టర్లు",
        reset: "రీసెట్",
        price_range: "ధర పరిధి",
        fabric: "వస్త్రం",
        apply: "వర్తించు",
        clear_filters: "ఫిల్టర్లను తొలగించు",
        material: "మెటీరియల్",
        color: "రంగు",
        pattern: "నమూనా",
        product_details: "ఉత్పత్తి వివరాలు",
        select_size: "సైజు ఎంచుకోండి",
        inclusive_taxes: "అన్ని పన్నులు కలుపుకొని",
        return_policy: "7 రోజుల రీప్లేస్‌మెంట్",
        cod_available: "క్యాష్ ఆన్ డెలివరీ",
        discount_off: "తగ్గింపు",
        account_settings: "ఖాతా సెట్టింగులు",
        log_out: "లాగ్ అవుట్",
        select_language: "భాషను ఎంచుకోండి",
        my_orders: "నా ఆర్డర్లు",
        my_wishlist: "నా విష్‌లిస్ట్",
        my_addresses: "నా చిరునామాలు",
        saved_addresses: "సేవ్ చేసిన చిరునామాలు",
        contact: "సంప్రదించండి",
        about_us: "మా గురించి",
        privacy_policy: "గోప్యతా విధానం",
        terms_policies: "నిబంధనలు",
        login_title: "లాగిన్",
        register_title: "రిజిస్టర్",
        items: "అంశాలు",
        sort: "సార్ట్",
        filter: "ఫిల్టర్",
        price: "ధర",
        add_to_cart: "కార్ట్‌కు జోడించు",
        buy_now: "కొనండి",
        search_hint: "వెతకండి...",
        order_placed: "ఆర్డర్ చేయబడింది!",
        order_confirmed_msg: "మీ ఆర్డర్ నిర్ధారించబడింది.",
        check_status: "ఆర్డర్ స్థితి",
        continue_shopping: "షాపింగ్ కొనసాగించు",
        payment_failed: "చెల్లింపు విఫలమైంది",
        try_again: "మళ్ళీ ప్రయత్నించు",
        no_results_for: "ఫలితాలు లేవు",
        empty_cart: "కార్ట్ ఖాళీగా ఉంది",
        empty_wishlist: "విష్‌లిస్ట్ ఖాళీగా ఉంది",
    }
};

// Fallback to English if key missing
const getTranslation = (lang: LanguageCode, key: string) => {
    return translations[lang]?.[key] || translations['en'][key] || key;
};

interface LanguageContextData {
    language: LanguageCode;
    setLanguage: (lang: LanguageCode) => Promise<void>;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextData>({} as LanguageContextData);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<LanguageCode>('en');

    useEffect(() => {
        loadLanguage();
    }, []);

    const loadLanguage = async () => {
        try {
            const stored = await AsyncStorage.getItem('app_language');
            if (stored) {
                setLanguageState(stored as LanguageCode);
            }
        } catch (e) {
            console.log('Failed to load language');
        }
    };

    const setLanguage = async (lang: LanguageCode) => {
        setLanguageState(lang);
        await AsyncStorage.setItem('app_language', lang);
    };

    const t = (key: string) => getTranslation(language, key);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
